### PR TITLE
Run npm install and git as a user, not root

### PR DESCRIPTION
**Pull request by nono**
From a security point of view, it's better to install npm modules not in root.

### CODE REVIEW

**Comment by nono** [comment]
It broke tests on travis :disappointed:

**Comment by aenario** [comment]
:+1: Travis is green and code looks great.

However, I feel this has the potential to break a lot of things.
@poupotte could you test it ? (specially Kresus)

**Comment by clochix** [comment]
Pinging @bnjbvr

**Comment by bnjbvr** [comment]
Good news this is getting fixed!

On the master branch: Kresus installs Weboob directly from node.js, so with the cozy-kresus user. As long as cozy-kresus has all rights (rwx) under kresus/, we should be all good here. I've had to manually chown beforehand, see also https://github.com/bnjbvr/kresus/blob/master/scripts/postinstall.sh . Testing would be good, though :D

Older versions of Kresus compiled all the source to JS at npm:postinstall. Again, as long as the build/ directory can be created and written by the user who runs the install, we should be fine.

**Comment by nledez** [comment]
Great feature! Thanks @nono :bowtie:

**Comment by aenario** [comment]
Ok, then I am ready to merge this, we will test it over the next sprint.

Would you mind rebasing it to removing debug / remove debug commits and opening the PR against development instead of master ?

**Comment by aenario** [comment]
My bad, development branch is unnecessary on cozy-controller as it is a npm package, I just removed it.

**Comment by nono** [comment]
@aenario debug commits has been squashed

**Comment by aenario** [comment]
Thanks @nono & sorry for the merge delay !

**Comment by bnjbvr** [comment]
Yay :+1:

**Comment by poupotte** [comment]
@bnjbvr : I tested an installation of kresus with this cozy-controller and I have some errors during dependencies installation.

I don't know if these errors are due to controller changes.

Here my logs : 
https://gist.github.com/poupotte/9825075ee6516d85d7f7

**Comment by nono** [comment]
@poupotte `ffi.h: No such file or directory` means that the package `libffi-dev` is missing (on debian). You'll probably also need `libyaml-dev libjpeg-dev python-virtualenv`.

**Comment by poupotte** [comment]
Ok, thanks. I'll see with @nledez because I tested on a cozy instance.

**Pull request merged**
