### PR TITLE
Debug autostart when app changes it port

### PR DESCRIPTION
**Pull request by poupotte**

### CODE REVIEW

**Comment by frankrousseau** [comment]
Could you add a tests about it?

**Comment by poupotte** [comment]
Wait travis test ....

**Comment by poupotte** [comment]
Before merge : can you merge/publish request-json-light. After that, I'll upgrade request-json-light version in package.json else [this request](https://github.com/cozy/cozy-controller/commit/81fe62199a3b5f4764e85c06d98f559ab62305dd#diff-5bf8ab4ca19a2b360187787a0b6eb825R47) cannot work. Thanks.

**Comment by frankrousseau** [comment]
The version of request-json-light is too old. That's why it doesn't work.

**Pull request merged**
