### PR TITLE
Use npm programmatrically and improve error sending

### PR DESCRIPTION
**Pull request by poupotte**

### CODE REVIEW

**Comment by bnjbvr** [comment]
Sorry I am too tired to make a PR tonight for addressing the issues I've spotted, but I think that this PR somehow (not sure about this, but this is a very likely hypothesis) implies that kresus' postinstall script isn't run anymore, resulting in ENOENT build/server.js (as dependencies are built at postinstall) when starting it... In a nutshell, all kresus installs/updates shall be broken because of this. I think Tasky is also affected. What could we do to mitigate the issue? (except for not using `postinstall`)

**Comment by poupotte** [comment]
Thanks @bnjbvr  for the report, I take care.

**Comment by frankrousseau** [comment]
We published a new version (2.0.22) could you try again @bnjbvr to install Kresus?

**Comment by bnjbvr** [comment]
Perfect, it works again! Thank you for the quick fixes!

**Comment by frankrousseau** [comment]
You're welcome!

**Pull request merged**
