### PR TITLE
Restart apps more than 5 times

### PR DESCRIPTION
**Pull request by nono**
Currently, I'm using a fork of forever-monitor to do that. I've made a PR, but I don't know if it will be accepted in a near future.

The PR: https://github.com/foreverjs/forever-monitor/pull/119

### CODE REVIEW

**Comment by frankrousseau** [comment]
Is it still a work in progress PR?

**Comment by nono** [comment]
Well, it works but maybe we should wait a bit to see if my PR for forever can be merged.

**Comment by aenario** [comment]
We have add problems with github npm dependencies before.  ( [Crap, i feel like the 5th monkey](http://i.snag.gy/kdu77.jpg) )

How about we publish a npm temporary fork ?

**Comment by nono** [comment]
@aenario yes, I think we should publish a npm temporary fork. I've received no feedback on my PR for forever. Can you do that?

**Comment by frankrousseau** [comment]
ping @aenario

**Comment by aenario** [comment]
Ok, published as cozy-forever-monitor v1.7.1
The repository is at https://github.com/cozy-labs/forever-monitor

**Comment by nono** [comment]
Thanks @aenario. I've updated this PR to use it.

**Pull request merged**
