### PR TITLE
Use readFile instead of require to recove last version

### PR DESCRIPTION
**Pull request by poupotte**
* Usefull for stack updating.

### CODE REVIEW

**Comment by poupotte** [comment]
When I use require, it doesn't update data after an application updating.

**Comment by jsilvestre** [comment]
I opened https://github.com/cozy/cozy-controller/pull/34 with @poupotte's "fix application icon" commit, because we need it this week.

**Comment by frankrousseau** [comment]
@poupotte What is the status of this PR?

**Comment by poupotte** [comment]
I thought this PR was already merged. 
I'm working on it to pass travis tests.

**Comment by poupotte** [comment]
You can merge if it's ok for you.

**Pull request merged**
